/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UiShowcaseRouteImport } from './routes/ui-showcase'
import { Route as TutorialsRouteImport } from './routes/tutorials'
import { Route as SharepointRouteImport } from './routes/sharepoint'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PowerappsRouteImport } from './routes/powerapps'
import { Route as PowerAutomateRouteImport } from './routes/power-automate'
import { Route as EnterpriseSolutionsRouteImport } from './routes/enterprise-solutions'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminPostsNewRouteImport } from './routes/admin.posts.new'
import { Route as AdminPostsIdEditRouteImport } from './routes/admin.posts.$id.edit'

const UiShowcaseRoute = UiShowcaseRouteImport.update({
  id: '/ui-showcase',
  path: '/ui-showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialsRoute = TutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => rootRouteImport,
} as any)
const SharepointRoute = SharepointRouteImport.update({
  id: '/sharepoint',
  path: '/sharepoint',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PowerappsRoute = PowerappsRouteImport.update({
  id: '/powerapps',
  path: '/powerapps',
  getParentRoute: () => rootRouteImport,
} as any)
const PowerAutomateRoute = PowerAutomateRouteImport.update({
  id: '/power-automate',
  path: '/power-automate',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseSolutionsRoute = EnterpriseSolutionsRouteImport.update({
  id: '/enterprise-solutions',
  path: '/enterprise-solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/admin/media',
  path: '/admin/media',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsNewRoute = AdminPostsNewRouteImport.update({
  id: '/admin/posts/new',
  path: '/admin/posts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsIdEditRoute = AdminPostsIdEditRouteImport.update({
  id: '/admin/posts/$id/edit',
  path: '/admin/posts/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/enterprise-solutions': typeof EnterpriseSolutionsRoute
  '/power-automate': typeof PowerAutomateRoute
  '/powerapps': typeof PowerappsRoute
  '/resources': typeof ResourcesRoute
  '/sharepoint': typeof SharepointRoute
  '/tutorials': typeof TutorialsRoute
  '/ui-showcase': typeof UiShowcaseRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/posts/$id/edit': typeof AdminPostsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/enterprise-solutions': typeof EnterpriseSolutionsRoute
  '/power-automate': typeof PowerAutomateRoute
  '/powerapps': typeof PowerappsRoute
  '/resources': typeof ResourcesRoute
  '/sharepoint': typeof SharepointRoute
  '/tutorials': typeof TutorialsRoute
  '/ui-showcase': typeof UiShowcaseRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/posts/$id/edit': typeof AdminPostsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/enterprise-solutions': typeof EnterpriseSolutionsRoute
  '/power-automate': typeof PowerAutomateRoute
  '/powerapps': typeof PowerappsRoute
  '/resources': typeof ResourcesRoute
  '/sharepoint': typeof SharepointRoute
  '/tutorials': typeof TutorialsRoute
  '/ui-showcase': typeof UiShowcaseRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/posts/$id/edit': typeof AdminPostsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/enterprise-solutions'
    | '/power-automate'
    | '/powerapps'
    | '/resources'
    | '/sharepoint'
    | '/tutorials'
    | '/ui-showcase'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/media'
    | '/blog/$slug'
    | '/admin/'
    | '/admin/posts/new'
    | '/admin/posts/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/enterprise-solutions'
    | '/power-automate'
    | '/powerapps'
    | '/resources'
    | '/sharepoint'
    | '/tutorials'
    | '/ui-showcase'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/media'
    | '/blog/$slug'
    | '/admin'
    | '/admin/posts/new'
    | '/admin/posts/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/enterprise-solutions'
    | '/power-automate'
    | '/powerapps'
    | '/resources'
    | '/sharepoint'
    | '/tutorials'
    | '/ui-showcase'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/media'
    | '/blog/$slug'
    | '/admin/'
    | '/admin/posts/new'
    | '/admin/posts/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EnterpriseSolutionsRoute: typeof EnterpriseSolutionsRoute
  PowerAutomateRoute: typeof PowerAutomateRoute
  PowerappsRoute: typeof PowerappsRoute
  ResourcesRoute: typeof ResourcesRoute
  SharepointRoute: typeof SharepointRoute
  TutorialsRoute: typeof TutorialsRoute
  UiShowcaseRoute: typeof UiShowcaseRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  BlogSlugRoute: typeof BlogSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPostsNewRoute: typeof AdminPostsNewRoute
  AdminPostsIdEditRoute: typeof AdminPostsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ui-showcase': {
      id: '/ui-showcase'
      path: '/ui-showcase'
      fullPath: '/ui-showcase'
      preLoaderRoute: typeof UiShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorials': {
      id: '/tutorials'
      path: '/tutorials'
      fullPath: '/tutorials'
      preLoaderRoute: typeof TutorialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sharepoint': {
      id: '/sharepoint'
      path: '/sharepoint'
      fullPath: '/sharepoint'
      preLoaderRoute: typeof SharepointRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/powerapps': {
      id: '/powerapps'
      path: '/powerapps'
      fullPath: '/powerapps'
      preLoaderRoute: typeof PowerappsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/power-automate': {
      id: '/power-automate'
      path: '/power-automate'
      fullPath: '/power-automate'
      preLoaderRoute: typeof PowerAutomateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise-solutions': {
      id: '/enterprise-solutions'
      path: '/enterprise-solutions'
      fullPath: '/enterprise-solutions'
      preLoaderRoute: typeof EnterpriseSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/admin/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts/new': {
      id: '/admin/posts/new'
      path: '/admin/posts/new'
      fullPath: '/admin/posts/new'
      preLoaderRoute: typeof AdminPostsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts/$id/edit': {
      id: '/admin/posts/$id/edit'
      path: '/admin/posts/$id/edit'
      fullPath: '/admin/posts/$id/edit'
      preLoaderRoute: typeof AdminPostsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EnterpriseSolutionsRoute: EnterpriseSolutionsRoute,
  PowerAutomateRoute: PowerAutomateRoute,
  PowerappsRoute: PowerappsRoute,
  ResourcesRoute: ResourcesRoute,
  SharepointRoute: SharepointRoute,
  TutorialsRoute: TutorialsRoute,
  UiShowcaseRoute: UiShowcaseRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  BlogSlugRoute: BlogSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPostsNewRoute: AdminPostsNewRoute,
  AdminPostsIdEditRoute: AdminPostsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
